### ISSUE TITLE
Extra auth callback 

### ISSUE THREAD

**Issue by Ripchanskiy** [milestep/Portal#58]
https://github.com/milestep/Portal/blob/26edb4c0bbfb891959851f358a68c3f09f3bbc89/app/controllers/api/v1/users_controller.rb#L4

У вас в api controller-е есть этот колбек. Он вызовется в users controller т.к последний от него унаследован и все родителиские колбеки отработают

**Comment by 0vermore** [comment]
В этом [коммите](https://github.com/milestep/Portal/pull/62/commits/83dd0e52925ff7bbdafe26b8bf1ec13306a04d5f) оставил колбек :authorized только в api controller-e. Теперь он вызывается для каждого контроллера один раз, а в контроллерах админа дополнительно проверяется роль.
